services:
  weaponsforge.gemini-cli:
    container_name: weaponsforge-gemini-cli
    image: weaponsforge/gemini-cli:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./projects:/opt/app/projects
    stdin_open: true
    tty: true
